package com.example.jetzone.presentation.screens.JetSearch.Components

import com.example.jetzone.R

fun getAllFighterJets(): List<FighterJetDetails> {
    return listOf(
        FighterJetDetails(
            id = 1,
            modelName = "F-16",
            imageRes = R.drawable.f16,
            fullName = "F-16 Fighting Falcon",
            topSpeed = "2,124 km/h",
            generation = "4th Gen",
            missiles = "AIM-120 AMRAAM, AIM-9 Sidewinder, AGM-65 Maverick",
            manufacturerCountry = "USA",
            countryFlagRes = R.drawable.flag_usa,
            firstFlight = "20 January 1974",
            height = "4.88 m",
            wingspan = "9.96 m",
            range = "4,220 km",
            threeDModelRoute = "3dmodel_f16"
        ),
        FighterJetDetails(
            id = 2,
            modelName = "F-22",
            imageRes = R.drawable.f22,
            fullName = "F-22 Raptor",
            topSpeed = "2,414 km/h",
            generation = "5th Gen",
            missiles = "AIM-120D, AIM-9X, GBU-32 JDAM",
            manufacturerCountry = "USA",
            countryFlagRes = R.drawable.flag_usa,
            firstFlight = "7 September 1997",
            height = "5.08 m",
            wingspan = "13.56 m",
            range = "2,960 km",
            threeDModelRoute = "3dmodel_f22"
        ),
        FighterJetDetails(
            id = 3,
            modelName = "Su-57",
            imageRes = R.drawable.su57,
            fullName = "Sukhoi Su-57",
            topSpeed = "2,600 km/h",
            generation = "5th Gen",
            missiles = "R-77M, R-74M2, Kh-59MK2",
            manufacturerCountry = "Russia",
            countryFlagRes = R.drawable.flag_russia,
            firstFlight = "29 January 2010",
            height = "4.74 m",
            wingspan = "14.10 m",
            range = "3,500 km",
            threeDModelRoute = "3dmodel_su57"
        ),
        FighterJetDetails(
            id = 4,
            modelName = "J-20",
            imageRes = R.drawable.j20,
            fullName = "Chengdu J-20",
            topSpeed = "2,100 km/h",
            generation = "5th Gen",
            missiles = "PL-15, PL-10, PL-21",
            manufacturerCountry = "China",
            countryFlagRes = R.drawable.flag_china,
            firstFlight = "11 January 2011",
            height = "4.69 m",
            wingspan = "12.88 m",
            range = "5,500 km",
            threeDModelRoute = "3dmodel_j20"
        ),
        FighterJetDetails(
            id = 18,
            modelName = "Su-30",
            imageRes = R.drawable.su30,
            fullName = "Sukhoi Su-30",
            topSpeed = "2,120 km/h",
            generation = "4++ Gen",
            missiles = "R-77, R-73, Kh-59",
            manufacturerCountry = "Russia",
            countryFlagRes = R.drawable.flag_russia,
            firstFlight = "31 December 1989",
            height = "6.36 m",
            wingspan = "14.70 m",
            range = "3,000 km",
            threeDModelRoute = "3dmodel_su30"
        ),
        FighterJetDetails(
            id = 14,
            modelName = "Mig-29",
            imageRes = R.drawable.mig29,
            fullName = "Mikoyan MiG-29",
            topSpeed = "2,400 km/h",
            generation = "4th Gen",
            missiles = "R-27, R-73, R-77",
            manufacturerCountry = "Russia",
            countryFlagRes = R.drawable.flag_russia,
            firstFlight = "6 October 1977",
            height = "4.73 m",
            wingspan = "11.36 m",
            range = "1,430 km",
            threeDModelRoute = "3dmodel_mig29"
        ),
        FighterJetDetails(
            id = 7,
            modelName = "F-35",
            imageRes = R.drawable.f35,
            fullName = "F-35 Lightning II",
            topSpeed = "1,930 km/h",
            generation = "5th Gen",
            missiles = "AIM-120D, AIM-9X, GBU-12 Paveway II",
            manufacturerCountry = "USA",
            countryFlagRes = R.drawable.flag_usa,
            firstFlight = "15 December 2006",
            height = "4.38 m",
            wingspan = "10.70 m",
            range = "2,200 km",
            threeDModelRoute = "3dmodel_f35"
        ),
        FighterJetDetails(
            id = 9,
            modelName = "Rafale",
            imageRes = R.drawable.rafale,
            fullName = "Dassault Rafale",
            topSpeed = "1,912 km/h",
            generation = "4.5 Gen",
            missiles = "MICA, Meteor, SCALP EG",
            manufacturerCountry = "France",
            countryFlagRes = R.drawable.flag_france,
            firstFlight = "4 July 1986",
            height = "5.34 m",
            wingspan = "10.90 m",
            range = "3,700 km",
            threeDModelRoute = "3dmodel_rafale"
        ),
        FighterJetDetails(
            id = 5,
            modelName = "Su-35",
            imageRes = R.drawable.su35,
            fullName = "Sukhoi Su-35",
            topSpeed = "2,400 km/h",
            generation = "4++ Gen",
            missiles = "R-77-1, R-74, Kh-31",
            manufacturerCountry = "Russia",
            countryFlagRes = R.drawable.flag_russia,
            firstFlight = "19 February 2008",
            height = "5.90 m",
            wingspan = "15.30 m",
            range = "3,600 km",
        ),
        FighterJetDetails(
            id = 6,
            modelName = "Su-37",
            imageRes = R.drawable.su37,
            fullName = "Sukhoi Su-37",
            topSpeed = "2,500 km/h",
            generation = "4++ Gen",
            missiles = "R-77, R-73, Kh-29",
            manufacturerCountry = "Russia",
            countryFlagRes = R.drawable.flag_russia,
            firstFlight = "2 April 1996",
            height = "5.93 m",
            wingspan = "14.70 m",
            range = "3,300 km",
        ),
        FighterJetDetails(
            id = 8,
            modelName = "Typhoon",
            imageRes = R.drawable.typhoon,
            fullName = "Eurofighter Typhoon",
            topSpeed = "2,495 km/h",
            generation = "4.5 Gen",
            missiles = "Meteor, IRIS-T, ASRAAM",
            manufacturerCountry = "Multinational (UK/Germany/Italy/Spain)",
            countryFlagRes = R.drawable.flag_uk,
            firstFlight = "27 March 1994",
            height = "5.28 m",
            wingspan = "10.95 m",
            range = "2,900 km",
        ),

        FighterJetDetails(
            id = 10,
            modelName = "JAS 39",
            imageRes = R.drawable.jas39,
            fullName = "Saab JAS 39 Gripen",
            topSpeed = "2,470 km/h",
            generation = "4th Gen",
            missiles = "IRIS-T, Meteor, RB 99",
            manufacturerCountry = "Sweden",
            countryFlagRes = R.drawable.flag_sweden,
            firstFlight = "9 December 1988",
            height = "4.50 m",
            wingspan = "8.40 m",
            range = "3,200 km",
        ),
        FighterJetDetails(
            id = 11,
            modelName = "MiG-35",
            imageRes = R.drawable.mig35,
            fullName = "Mikoyan MiG-35",
            topSpeed = "2,400 km/h",
            generation = "4++ Gen",
            missiles = "R-77, R-73, Kh-35",
            manufacturerCountry = "Russia",
            countryFlagRes = R.drawable.flag_russia,
            firstFlight = "7 February 2007",
            height = "5.00 m",
            wingspan = "12.00 m",
            range = "2,000 km",
        ),
        FighterJetDetails(
            id = 12,
            modelName = "F/A-18",
            imageRes = R.drawable.f18,
            fullName = "F/A-18 Hornet",
            topSpeed = "1,915 km/h",
            generation = "4th Gen",
            missiles = "AIM-120, AIM-9, AGM-84",
            manufacturerCountry = "USA",
            countryFlagRes = R.drawable.flag_usa,
            firstFlight = "18 November 1978",
            height = "4.66 m",
            wingspan = "11.43 m",
            range = "2,000 km",
        ),
        FighterJetDetails(
            id = 13,
            modelName = "F-15",
            imageRes = R.drawable.f15,
            fullName = "F-15 Eagle",
            topSpeed = "2,655 km/h",
            generation = "4th Gen",
            missiles = "AIM-120, AIM-7, AIM-9",
            manufacturerCountry = "USA",
            countryFlagRes = R.drawable.flag_usa,
            firstFlight = "27 July 1972",
            height = "5.63 m",
            wingspan = "13.05 m",
            range = "3,900 km",
        ),
        FighterJetDetails(
            id = 15,
            modelName = "F-104",
            imageRes = R.drawable.f104,
            fullName = "F-104",
            topSpeed = "2,337 km/h",
            generation = "2nd Gen",
            missiles = "AIM-9, AIM-7",
            manufacturerCountry = "USA",
            countryFlagRes = R.drawable.flag_usa,
            firstFlight = "4 March 1954",
            height = "4.11 m",
            wingspan = "6.36 m",
            range = "2,400 km",
        ),
        FighterJetDetails(
            id = 16,
            modelName = "Mirage 2000",
            imageRes = R.drawable.mirage2000,
            fullName = "Mirage 2000",
            topSpeed = "2,336 km/h",
            generation = "4th Gen",
            missiles = "MICA, Magic II, SCALP EG",
            manufacturerCountry = "France",
            countryFlagRes = R.drawable.flag_france,
            firstFlight = "10 March 1978",
            height = "5.13 m",
            wingspan = "9.13 m",
            range = "1,550 km",
        ),
        FighterJetDetails(
            id = 17,
            modelName = "F-5",
            imageRes = R.drawable.f5,
            fullName = "F-5 Tiger II",
            topSpeed = "1,700 km/h",
            generation = "3rd Gen",
            missiles = "AIM-9, AGM-65",
            manufacturerCountry = "USA",
            countryFlagRes = R.drawable.flag_usa,
            firstFlight = "30 July 1959",
            height = "4.06 m",
            wingspan = "8.13 m",
            range = "1,405 km",
        ),
        FighterJetDetails(
            id = 19,
            modelName = "A10c",
            imageRes = R.drawable.a10c,
            fullName = "A-10C",
            topSpeed = "706 km/h",
            generation = "3rd Gen",
            missiles = "AGM-65 Maverick, AIM-9 Sidewinder",
            manufacturerCountry = "USA",
            countryFlagRes = R.drawable.flag_usa,
            firstFlight = "10 May 1972",
            height = "4.47 m",
            wingspan = "17.53 m",
            range = "4,150 km",
            threeDModelRoute = "3dmodel_a10c"
        ),
        FighterJetDetails(
            id = 20,
            modelName = "B-1 Lancer",
            imageRes = R.drawable.b1,
            fullName = "B-1 Lancer",
            topSpeed = "1,448 km/h",
            generation = "4th Gen",
            missiles = "AGM-158 JASSM, AGM-158C LRASM",
            manufacturerCountry = "USA",
            countryFlagRes = R.drawable.flag_usa,
            firstFlight = "23 December 1974",
            height = "17.78 m",
            wingspan = "41.67 m (extended), 23.84 m (swept)",
            range = "12,000 km",
            threeDModelRoute = "3dmodel_b1"
        ),
        FighterJetDetails(
            id = 21,
            modelName = "B-2 Spirit",
            imageRes = R.drawable.b2,
            fullName = "B-2 Spirit",
            topSpeed = "1,010 km/h",
            generation = "5th Gen",
            missiles = "B61 nuclear bomb, AGM-129 ACM",
            manufacturerCountry = "USA",
            countryFlagRes = R.drawable.flag_usa,
            firstFlight = "17 July 1989",
            height = "17.1 m",
            wingspan = "52.4 m",
            range = "11,100 km",
            threeDModelRoute = "3dmodel_b2"
        ),
        FighterJetDetails(
            id = 22,
            modelName = "F-117",
            imageRes = R.drawable.f117,
            fullName = "F-117 Nighthawk",
            topSpeed = "993 km/h",
            generation = "4th Gen",
            missiles = "GBU-10 Paveway II, GBU-27 Paveway III",
            manufacturerCountry = "USA",
            countryFlagRes = R.drawable.flag_usa,
            firstFlight = "18 June 1981",
            height = "3.78 m",
            wingspan = "13.20 m",
            range = "1,720 km",
            threeDModelRoute = "3dmodel_f117"
        ),
        FighterJetDetails(
            id = 23,
            modelName = "Xi'an H-6",
            imageRes = R.drawable.bomber_h6,
            fullName = "Xi'an H-6",
            topSpeed = "1,050 km/h",
            generation = "2nd Gen",
            missiles = "CJ-10 cruise missile, KD-63",
            manufacturerCountry = "China",
            countryFlagRes = R.drawable.flag_china,
            firstFlight = "1959",
            height = "10.36 m",
            wingspan = "32.99 m",
            range = "6,000 km",
            threeDModelRoute = "3dmodel_h6"
        ),
        FighterJetDetails(
            id = 24,
            modelName = "J-31",
            imageRes = R.drawable.j31,
            fullName = "Shenyang J-31",
            topSpeed = "2,200 km/h",
            generation = "5th Gen",
            missiles = "PL-12, PL-15, PL-21",
            manufacturerCountry = "China",
            countryFlagRes = R.drawable.flag_china,
            firstFlight = "31 October 2012",
            height = "4.8 m",
            wingspan = "11.5 m",
            range = "1,250 km",
            threeDModelRoute = "3dmodel_j31"
        ),
        FighterJetDetails(
            id = 25,
            modelName = "J-36",
            imageRes = R.drawable.j36,
            fullName = "J-36",
            topSpeed = "2,500 km/h",
            generation = "6th Gen",
            missiles = "PL-XX",
            manufacturerCountry = "China",
            countryFlagRes = R.drawable.flag_china,
            firstFlight = "N/A",
            height = "N/A",
            wingspan = "N/A",
            range = "3,000 km",
            threeDModelRoute = "3dmodel_j36"
        ),
        FighterJetDetails(
            id = 26,
            modelName = "MiG-1.44",
            imageRes = R.drawable.mig144,
            fullName = "Mikoyan MiG-1.44",
            topSpeed = "2,600 km/h",
            generation = "5th Gen",
            missiles = "R-77, R-73, R-37M",
            manufacturerCountry = "Russia",
            countryFlagRes = R.drawable.flag_russia,
            firstFlight = "29 February 2000",
            height = "4.50 m",
            wingspan = "15.00 m",
            range = "4,000 km",
            threeDModelRoute = "3dmodel_mig144"
        ),
        FighterJetDetails(
            id = 27,
            modelName = "SR-71",
            imageRes = R.drawable.sr71,
            fullName = "SR-71 Blackbird",
            topSpeed = "3,540 km/h",
            generation = "3rd Gen",
            missiles = "None",
            manufacturerCountry = "USA",
            countryFlagRes = R.drawable.flag_usa,
            firstFlight = "22 December 1964",
            height = "5.64 m",
            wingspan = "16.94 m",
            range = "5,400 km",
            threeDModelRoute = "3dmodel_sr71"
        ),
        FighterJetDetails(
            id = 28,
            modelName = "Su-34",
            imageRes = R.drawable.su34,
            fullName = "Sukhoi Su-34",
            topSpeed = "1,900 km/h",
            generation = "4++ Gen",
            missiles = "Kh-29, Kh-31, Kh-59",
            manufacturerCountry = "Russia",
            countryFlagRes = R.drawable.flag_russia,
            firstFlight = "13 April 1990",
            height = "5.93 m",
            wingspan = "14.70 m",
            range = "4,000 km",
            threeDModelRoute = "3dmodel_su34"
        ),
        FighterJetDetails(
            id = 29,
            modelName = "Su-47",
            imageRes = R.drawable.su47,
            fullName = "Sukhoi Su-47",
            topSpeed = "2,200 km/h",
            generation = "5th Gen",
            missiles = "R-77, R-73, R-37",
            manufacturerCountry = "Russia",
            countryFlagRes = R.drawable.flag_russia,
            firstFlight = "25 Sep 1997",
            height = "6.30 m",
            wingspan = "16.70 m",
            range = "3,300 km",
            threeDModelRoute = "3dmodel_su47"
        ),
        FighterJetDetails(
            id = 30,
            modelName = "Su-75",
            imageRes = R.drawable.su75,
            fullName = "Sukhoi Su-75",
            topSpeed = "2,100 km/h",
            generation = "5th Gen",
            missiles = "R-77M, R-74M2",
            manufacturerCountry = "Russia",
            countryFlagRes = R.drawable.flag_russia,
            firstFlight = "2023 (planned)",
            height = "4.5 m",
            wingspan = "11.5 m",
            range = "3,000 km",
            threeDModelRoute = "3dmodel_su75"
        ),
        FighterJetDetails(
            id = 31,
            modelName = "Tu-95",
            imageRes = R.drawable.tu95,
            fullName = "Tupolev Tu-95",
            topSpeed = "925 km/h",
            generation = "1st Gen",
            missiles = "Kh-55, Kh-101 cruise missiles",
            manufacturerCountry = "Russia",
            countryFlagRes = R.drawable.flag_russia,
            firstFlight = "12 November 1952",
            height = "12.12 m",
            wingspan = "50.10 m",
            range = "15,000 km",
            threeDModelRoute = "3dmodel_tu95"
        ),
        FighterJetDetails(
            id = 32,
            modelName = "Tu-22",
            imageRes = R.drawable.tu22,
            fullName = "Tupolev Tu-22M",
            topSpeed = "2,300 km/h",
            generation = "3rd Gen",
            missiles = "Kh-22, Kh-15, Kh-47M2 Kinzhal",
            manufacturerCountry = "Russia",
            countryFlagRes = R.drawable.flag_russia,
            firstFlight = "30 August 1969",
            height = "11.05 m",
            wingspan = "34.28 m (extended), 23.30 m (swept)",
            range = "6,800 km",
            threeDModelRoute = "3dmodel_tu22"
        ),
        FighterJetDetails(
            id = 33,
            modelName = "YF-23",
            imageRes = R.drawable.yf23,
            fullName = "YF-23",
            topSpeed = "2,650 km/h",
            generation = "5th Gen",
            missiles = "AIM-120 AMRAAM",
            manufacturerCountry = "USA",
            countryFlagRes = R.drawable.flag_usa,
            firstFlight = "27 August 1990",
            height = "4.34 m",
            wingspan = "13.34 m",
            range = "4,350 km",
            threeDModelRoute = "3dmodel_yf23"
        )
    )
}